### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by LongfeiProjects** [kschwan/pyreflexxes#1]
I got some compile error msgs while installing this package. You may try to add few lines in CMakeLists.txt file to get avoid of it:

> cmake_minimum_required(VERSION 3.1)
   project(pyreflexxes)
  +set(CMAKE_CXX_STANDARD 14)
  +set(CMAKE_CXX_STANDARD_REQUIRED ON)
  +set(CMAKE_CXX_EXTENSIONS OFF)

Hope this may save a bit time for others who are not familiar with cmake and compling stuff.

**Comment by kschwan** [comment]
Thanks!

On Ubuntu 20.04 using pybind11 v2.4.3 from APT repos, `-std=c++14` is set automatically ~~by `pybind11_add_module`~~, but I guess it might not be the same for all systems. I'll add it to the CMakeLists.txt as you propose :+1:

**Comment by LongfeiProjects** [comment]
You are right, I am using Ubuntu18.04, kinda old-fashioned

**Comment by kschwan** [comment]
I realised that probably C++14 is set automatically not by `pybind11_add_module` but simply by using a newer version of GCC.
